### ISSUE TITLE
Fault node does not support assigning fields of a record type (composite structure)

### ISSUE THREAD

**Issue by janetlj** [loonwerks/AMASE#2]
The fault node currently does not support passing fields of a record type as input or output arguments of a fault node. Users have to pass the record type as a whole, and use record update expression inside the fault node definition in order to assign individual fields (e.g., fault "AILL INVERT FAIL" in https://github.com/loonwerks/AMASE/blob/develop/examples/QFCS_V3/packages/OSAS.aadl).

There should be a validator error preventing users from passing fields of a record type to a fault node in the editor before this capability is supported.

**Comment by dkstewart** [comment]
Record types are now supported.
